name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: addx
      run: |
        chmod +x ./download_voicevox_core.csx
        ls -l
    - name: Download voicevox_core
      run: |
        : # chmod +x ./download_voicevox_core.csx
        dotnet script ./download_voicevox_core.csx
    - name: Test
      run: dotnet test --no-build --verbosity normal
